version: "3.8"
services:

  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    networks:
      - prod

  db:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
        - prod

  phpmyadmin:
    image: phpmyadmin
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
        - db
    ports:
        - 8088:80
    environment:
        PMA_HOST: db
    networks:
        - prod

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: "always"
    networks:
      - prod
      
  composer:
    image: composer
    container_name: composer_docker_symfony
    restart: always
    volumes:
      - /var/www/project:/app
    networks:
      - prod

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
        - ./php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always
    networks:
        - prod


networks:
  prod:

volumes:
  db-data:
